name: "Organizer App"
description: "Personal Organization Platform"
version: "1.0.0"
slug: "organizer"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Web interface"
webui: "http://[HOST]:[PORT:8099]"
ingress: true
ingress_port: 8099
panel_icon: mdi:view-dashboard
panel_title: Organizer
hassio_api: false
homeassistant_api: true
