apiVersion: apps/v1
kind: Deployment
metadata:
  name: organizer-app
  labels:
    app: organizer-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: organizer-app
  template:
    metadata:
      labels:
        app: organizer-app
    spec:
      containers:
      - name: organizer-app
        image: organizer-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: NUXT_HOST
          value: "0.0.0.0"
        - name: NUXT_PORT
          value: "3000"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
