apiVersion: v1
kind: Service
metadata:
  name: organizer-app
  labels:
    app: organizer-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: organizer-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: organizer-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: organizer.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: organizer-app
            port:
              number: 80
